DO $$ BEGIN
 CREATE TYPE "public"."usage_rights" AS ENUM('OWNER', 'LICENSED', 'CREATIVE_COMMONS', 'PUBLIC_DOMAIN', 'FAIR_USE', 'THIRD_PARTY_CONTENT', 'CONTENT_ID_MATCHED', 'UNSPECIFIED');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
