import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getUserTeams } from "@/auth";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId = "1";
  const teams = await getUserTeams(userId);
  const channels: any[] = []
  // const channels = await getUserChannels(teams[0].teamId);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen`}
      >
        <aside className="w-64 bg-gray-800 text-white p-6">
          <div className=" flex space-x-4 items-center justify-center mb-4 border-b border-gray-600 pb-4">
            <Link className="ring-2 ring-gray-400 hover:ring-gray-300 cursor-pointer rounded-md p-2 w-full" href="/">Home</Link>
            <Link className="ring-2 ring-gray-400 hover:ring-gray-300 cursor-pointer rounded-md p-2 w-full" href="/login">Login</Link>
          </div>
          <h1 className="text-2xl font-bold my-2">Teams</h1>
          {teams.length === 0 && (
            <div>
              <h2 className="text-sm mb-2 text-gray-400">No teams found</h2>
            </div>
          )}
          {teams.map((team) => (
            <div key={team.teamId}>
              <h2 className="text-lg font-bold mb-2">{team.teamName}</h2>
            </div>

          ))}
          <nav>
            <h2 className="text-lg font-bold mb-2">Channels</h2>
            {channels.length === 0 && (
              <div>
                <h2 className="text-sm mb-2 text-gray-400">No channels found</h2>
              </div>
            )}
            {channels.map((channel) => (
              <div key={channel.channelId}>
                <h2 className="text-lg font-bold mb-2">{channel.channelName}</h2>
                {/* Add channel list here */}
              </div>
            ))}
          </nav>
        </aside>
        <main className="flex-1 p-8 overflow-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
